### ISSUE TITLE
fix indentation, remove ;

### ISSUE THREAD

**Issue by nkiesel** [upendrac1984/RestAssured_Testing#4]
https://github.com/upendrac1984/RestAssured_Testing/blob/5652ae7d02a91e18a8d3bd055c031f712ee4e650/src/test/groovy/com/restassured/Request.groovy#L6

**Comment by nkiesel** [comment]
actually not just for line 6 but whole class

**Comment by upendrac1984** [comment]
modified indentation and removed unwanted colons.
