### ISSUE TITLE
better path name validations

### ISSUE THREAD

**Issue by nkiesel** [upendrac1984/RestAssured_Testing#8]
https://github.com/upendrac1984/RestAssured_Testing/blob/5652ae7d02a91e18a8d3bd055c031f712ee4e650/src/test/groovy/com/restassured/RestAPIThreadExecutor.groovy#L146

we should restrict `queryFile` (e.g. no `..`).  Also could make use of Java8 path API (if Java 8 is the lowest Java version supported).  Oh, and these `InputStream` are never closed.

**Comment by upendrac1984** [comment]
used path API for better path construction
